# Work around the TLAS input-layout bug in pinned NVRHI dafbd407f6fb.
# Compile a corrected build-tree copy so submodule contents and revision stay clean.
function(neuraldoom_fix_nvrhi_raytracing)
    get_target_property(nvrhi_source_dir nvrhi_d3d12 SOURCE_DIR)
    set(original "${nvrhi_source_dir}/src/d3d12/d3d12-raytracing.cpp")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${original}")
    file(READ "${original}" source_text)
    string(REPLACE "\r\n" "\n" source_text "${source_text}")
    set(old_storage "        } m_desc;")
    set(old_instances "            m_desc.InstanceDescs = instanceDescs;\n            m_desc.NumDescs = numDescs;")
    foreach(expected IN ITEMS "${old_storage}" "${old_instances}")
        string(FIND "${source_text}" "${expected}" match_position)
        if(match_position EQUAL -1)
            message(FATAL_ERROR "NVRHI RT source changed; review neo/cmake/NvrhiRayTracingFix.cmake before building")
        endif()
    endforeach()
    string(REPLACE "${old_storage}" "        } m_desc = {};" source_text "${source_text}")
    string(REPLACE "${old_instances}" "${old_instances}\n            m_desc.DescsLayout = D3D12_ELEMENTS_LAYOUT_ARRAY;" source_text "${source_text}")
    set(patched "${CMAKE_CURRENT_BINARY_DIR}/neuraldoom-nvrhi/d3d12-raytracing.cpp")
    file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/neuraldoom-nvrhi")
    file(WRITE "${patched}.tmp" "${source_text}")
    configure_file("${patched}.tmp" "${patched}" COPYONLY)
    get_target_property(dx12_sources nvrhi_d3d12 SOURCES)
    set(replaced FALSE)
    set(corrected_sources)
    foreach(source IN LISTS dx12_sources)
        if(source MATCHES "(^|/)d3d12-raytracing\\.cpp$")
            list(APPEND corrected_sources "${patched}")
            set(replaced TRUE)
        else()
            list(APPEND corrected_sources "${source}")
        endif()
    endforeach()
    if(NOT replaced)
        message(FATAL_ERROR "NVRHI DX12 target no longer contains the expected ray-tracing translation unit")
    endif()
    set_property(TARGET nvrhi_d3d12 PROPERTY SOURCES "${corrected_sources}")
    target_include_directories(nvrhi_d3d12 PRIVATE "${nvrhi_source_dir}/src/d3d12")
endfunction()
